### ISSUE TITLE
I have deployed socioboard on a domain name. Everything is working on local host. But when i try registering a user or perform some crud on online socioboard domain it returns 400 bad request cant add user!! The crud operations are working on localhost however. I dEPLOYED IT ON AWS

### ISSUE THREAD

**Issue by DibyankP** [socioboard/Socioboard-5.0#100]

**Comment by Basanagoudaglb** [comment]
most probably, there is some issues in your database connection. please check whether it is working on your sever.

**Comment by socioboard** [comment]
Hi, I hope you **look into the Latest 5.0 version**, and **we're giving weekly update** as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
