### ISSUE TITLE
https://ipapi.co/json/

### ISSUE THREAD

**Issue by escit** [socioboard/Socioboard-5.0#146]
https://ipapi.co/json/ error

**Comment by escit** [comment]
http://ip-api.com/json/

**Comment by sureshbabu1995** [comment]
Hi, @escit 

May I know where you facing this Issue?

**Comment by socioboard** [comment]
Could you please elaborate  your issue.

**Comment by socioboard** [comment]
Hi, I hope you **look into the Latest 5.0 version**, and **we're giving weekly update** as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
