### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by TechnologyClassroom** [socioboard/Socioboard-5.0#149]
This git does not mention the license from the official webpage except for another issue https://github.com/socioboard/Socioboard-4.0/issues/46. The default is copyright.

The https://socioboard.org/license/ page says, "The GPLv3 (or later) from the Free Software Foundation is the license that the Socioboard software is under its text follows."

I made a pull request to get the process started.  https://github.com/socioboard/Socioboard-4.0/pull/105

**Comment by sureshbabu1995** [comment]
Hi, @TechnologyClassroom 

Sorry for the inconvenience, Shortly we'll update the files with the license.

**Comment by TechnologyClassroom** [comment]
This PR is the start of it: https://github.com/socioboard/Socioboard-4.0/pull/105

**Comment by r0bbie** [comment]
A bit concerning there's still no license specified. To confirm, this is GPLv3 licensed software then? Would be helpful to add licenses to your repositories which are GPL licensed or otherwise.

**Comment by TechnologyClassroom** [comment]
@r0bbie I am not sure how the licensing of this works in this case.  It seems kind of ambiguous.  The website lists GPL-3.0-or-later, but the repo does not.  I made a PR to get it started back on Aug 8, 2019.  I did not hear back so I made this issue.

**Comment by socioboard** [comment]
Hi, I hope you look into the Latest 5.0 version, and we're giving weekly update as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..

**Comment by TechnologyClassroom** [comment]
[I searched the code for license and this issue has not been resolved.](https://github.com/socioboard/Socioboard-5.0/search?p=1&q=license)  Reopen.

**Comment by TechnologyClassroom** [comment]
PR https://github.com/socioboard/Socioboard-5.0/pull/105 associated with this issue was also closed.

I am not touching this code base again until the licensing issue is clarified.

**Comment by TechnologyClassroom** [comment]
This issue was resolved in https://github.com/socioboard/Socioboard-5.0/pull/245/

Thank you!
