### ISSUE TITLE
Error running node app.js at user microservice

### ISSUE THREAD

**Issue by lombmartgh** [socioboard/Socioboard-5.0#163]
Hello, 

I'm trying to run "node app.js" in socioboard-api\user microservice folder. Fallowing the documentation, for Socioboard4.0 in development mode.

But I'm getting this error that don't allow me to continue with the installation.

{ message:
   'The "path" argument must be one of type string, Buffer, or URL. Received type object',
  level: 'error',
  timestamp: '2020-04-17T23:31:59.680Z' }

I had search for some way to get the debug information more specific, but no success. Do you have any idea?

This is my complete user log;

{ message: 'Cron setup intialized for monthly user stats...',
  level: 'info',
  timestamp: '2020-04-17T23:31:57.272Z' }
{ message: 'Mongo Database has been connected.',
  level: 'info',
  timestamp: '2020-04-17T23:31:59.487Z' }
{ message: 'Sequelize Database has been connected.',
  level: 'info',
  timestamp: '2020-04-17T23:31:59.618Z' }
{ message:
   'The "path" argument must be one of type string, Buffer, or URL. Received type object',
  level: 'error',
  timestamp: '2020-04-17T23:31:59.680Z' }

I'm using:
Windows 10
node v10.15.1
nodemon v2.0.3

**Comment by sureshbabu1995** [comment]
Hi, @lombmartgh 

As of code, there's no variable called path .. but if you using VsCode for editing node code, please search for a path variable in user microservices and if you found it it might contain in mostly an environmental JSON file please follow the standard of it ( keeping the key and values in double-quotes )...

I hope this will solve your issue.

and your system config is proper, you don't have any problem with the system configuration

**Comment by vaaiibhav** [comment]
i have different error at same location


{
  message: 'Cron setup intialized for monthly user stats...',
  level: 'info',
  timestamp: '2020-04-27T09:29:36.744Z'
}
{
  message: 'Mongo Database has been connected.',
  level: 'info',
  timestamp: '2020-04-27T09:29:38.863Z'
}
{
  message: 'Sequelize Database has been connected.',
  level: 'info',
  timestamp: '2020-04-27T09:29:38.960Z'
}
{
  message: 'Configuration property "payment.base_path" is not defined',
  level: 'error',
  timestamp: '2020-04-27T09:29:39.032Z'
}

**Comment by sureshbabu1995** [comment]
Hi, @vaaiibhav  I've cleared your error in your Bug Please check it ...
