### ISSUE TITLE
Unable to add facebook account

### ISSUE THREAD

**Issue by yogesh23021995** [socioboard/Socioboard-5.0#164]
Can anybody please help to this issue while adding account to Facebook.

![Screenshot_3](https://user-images.githubusercontent.com/50060627/79891467-a6c47680-841e-11ea-9c1e-76cbdfe65184.png)

**Comment by sureshbabu1995** [comment]
Hi, @yogesh23021995 
in facebook API config 
add 
`"page_scopes": "email,user_posts,user_birthday,publish_pages,manage_pages,publish_to_groups",` under the scopes line.

**Comment by bhuvnesht26** [comment]
> Hi, @yogesh23021995
> in facebook API config
> add
> `"page_scopes": "email,user_posts,user_birthday,publish_pages,manage_pages,publish_to_groups",` under the scopes line.

Can you please tell the location of file where this change has to be made?

**Comment by lmahendra** [comment]
> > Hi, @yogesh23021995
> > in facebook API config
> > add
> > `"page_scopes": "email,user_posts,user_birthday,publish_pages,manage_pages,publish_to_groups",` under the scopes line.
> 
> Can you please tell the location of file where this change has to be made?

Facing same issue, I tried adding it in `user/config/development.json` next to scopes under facebook_api config but no success.
Did you have any luck configuring it?

**Comment by socioboard** [comment]
Hi, I hope you **look into the Latest 5.0 version**, and **we're giving weekly update** as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
