### ISSUE TITLE
nodemon stuck in users

### ISSUE THREAD

**Issue by vaaiibhav** [socioboard/Socioboard-5.0#165]
this is my users log file.
I am installing on windows 10 soicoboard-4.0 and node- v = 12.13.1

{
  message: 'Cron setup intialized for monthly user stats...',
  level: 'info',
  timestamp: '2020-04-27T09:29:36.744Z'
}
{
  message: 'Mongo Database has been connected.',
  level: 'info',
  timestamp: '2020-04-27T09:29:38.863Z'
}
{
  message: 'Sequelize Database has been connected.',
  level: 'info',
  timestamp: '2020-04-27T09:29:38.960Z'
}
{
  message: 'Configuration property "payment.base_path" is not defined',
  level: 'error',
  timestamp: '2020-04-27T09:29:39.032Z'
}

**Comment by sureshbabu1995** [comment]
Hi, @vaaiibhav 

Please add these 3 lines in the `development.json` file 

![image](https://user-images.githubusercontent.com/55544386/80453868-b7a54880-8946-11ea-8078-34ec95960517.png)

**Comment by gpellejero** [comment]
Hi all,
I am installing on Ubuntu 18.04 and node -v 10.20.1

I am having the same issue with "users", but couldn't solve it adding the 3 lines.The message is still appearing.

On the other part, I obtain the following answer when executing _nodemon app.js_ in every microservice:

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node app.js`
[nodemon] clean exit - waiting for changes before restart

Any idea?
Thanks in advance

**Comment by gpellejero** [comment]
Hi again,
I re-installed everything from the beginning.
When I execute "nodemon" in "users" folder there is no error, but I get "[nodemon] clean exit - waiting for changes before restart" in every folder.
Please, give me advise.
Thanks in advance

**Comment by sureshbabu1995** [comment]
Hi, 

In this scenario, you'll get some logs in the log file if you provide the log details I can help with that.

**Comment by bhuvnesht26** [comment]
**Facing the same issue and here is a snapshot of the log.**
@sureshbabu1995 

![image](https://user-images.githubusercontent.com/4116233/91196762-6f2e4980-e6f2-11ea-9f24-195f11a7126c.png)

**Comment by hcortez-bit** [comment]
before putting the 3 lines after the penultimate key it has ","

**Comment by semiPlanet** [comment]
do not use nodemon use npm
npm install -g pm2@latest
npm start

**Comment by socioboard** [comment]
Hi, I hope you **look into the Latest 5.0 version**, and **we're giving weekly update** as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
