### ISSUE TITLE
mysql2 Error on installing Socioboard4 on Ubuntu 18.04.3

### ISSUE THREAD

**Issue by rodenp** [socioboard/Socioboard-5.0#168]
When i follow the installation instructions i get errors when i try to:

1. Run the sequelize command(s)
2. PHP installation, composer global require laravel/installer

When i run the command: sequelize db:migrate

I get the following results:

Sequelize CLI [Node: 8.10.0, CLI: 5.5.1, ORM: 5.21.10]

Loaded configuration file "config/config.json".
Using environment "development".

ERROR: Please install mysql2 package manually

I also get the same results when i run the command  sequelize db:seed --seed 20190213051930-initialize_application_info.js

2. PHP Installation

Running composer global require laravel/installer informs me that the Command 'composer' not found, but can be installed with:

apt install composer

After i install composer and rerun the composer command, i get the following messages:

Changed current directory to /root/.config/composer
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Using version ^3.1 for laravel/installer
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laravel/installer ^3.1 -> satisfiable by laravel/installer[v3.1.0].
    - laravel/installer v3.1.0 requires ext-zip * -> the requested PHP extension zip is missing from your system.

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.2/cli/php.ini
    - /etc/php/7.2/cli/conf.d/10-opcache.ini
    - /etc/php/7.2/cli/conf.d/10-pdo.ini
    - /etc/php/7.2/cli/conf.d/20-calendar.ini
    - /etc/php/7.2/cli/conf.d/20-ctype.ini
    - /etc/php/7.2/cli/conf.d/20-exif.ini
    - /etc/php/7.2/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.2/cli/conf.d/20-ftp.ini
    - /etc/php/7.2/cli/conf.d/20-gettext.ini
    - /etc/php/7.2/cli/conf.d/20-iconv.ini
    - /etc/php/7.2/cli/conf.d/20-json.ini
    - /etc/php/7.2/cli/conf.d/20-phar.ini
    - /etc/php/7.2/cli/conf.d/20-posix.ini
    - /etc/php/7.2/cli/conf.d/20-readline.ini
    - /etc/php/7.2/cli/conf.d/20-shmop.ini
    - /etc/php/7.2/cli/conf.d/20-sockets.ini
    - /etc/php/7.2/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.2/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.2/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.2/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, deleting ./composer.json.

**Comment by sureshbabu1995** [comment]
Hi, @rodenp 
For 
> ERROR: Please install mysql2 package manually, this 

you can try to install it using `npm install mysql2 -g` or you can try to use it like `npx sequelize db:migrate` command for direct installation.


2. PHP installation: 
![image](https://user-images.githubusercontent.com/55544386/83103170-d167b600-a0d3-11ea-9357-8a20a556a971.png)
you can try something like this ...

I hope these 2 things can help you to set up the Code.

**Comment by socioboard** [comment]
Hi, I hope you **look into the Latest 5.0 version**, and **we're giving weekly update** as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
