### ISSUE TITLE
Microservices are not running properly

### ISSUE THREAD

**Issue by lmahendra** [socioboard/Socioboard-5.0#183]
Hi,
I installed socioboard using link https://www.linuxbabe.com/ubuntu/install-socioboard-on-ubuntu-20-04 
Everything works fine except when I try to register an user, I am facing below error
`[2020-08-22 17:53:56] local.INFO: Sign up Exception 200 => cURL error 7: Failed to connect to localhost port 3000: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)  
[2020-08-22 17:53:56] local.ERROR: Undefined variable: result {"exception":"[object] (ErrorException(code: 0): Undefined variable: result at /var/www/socioboard/socioboard-web-php/app/Modules/User/Controllers/UserController.php:132)
[stacktrace]
#0 /var/www/socioboard/socioboard-web-php/app/Modules/User/Controllers/UserController.php(132): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
`

I checked if microservices are working, but it seems it stopped at ` [nodemon] starting `node app.js``
Below is the status of socioboard-user

`socioboard-user.service - SocioBoard User Microservice
   Loaded: loaded (/etc/systemd/system/socioboard-user.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-08-22 17:34:27 UTC; 23min ago
 Main PID: 1324 (node)
    Tasks: 22 (limit: 2348)
   CGroup: /system.slice/socioboard-user.service
           ├─1324 node /usr/bin/nodemon app.js
           └─1442 /usr/bin/node app.js

Aug 22 17:34:27 ip-172-31-30-209 systemd[1]: Started SocioBoard User Microservice.
Aug 22 17:34:28 ip-172-31-30-209 nodemon[1324]: [nodemon] 2.0.4
Aug 22 17:34:28 ip-172-31-30-209 nodemon[1324]: [nodemon] to restart at any time, enter `rs`
Aug 22 17:34:28 ip-172-31-30-209 nodemon[1324]: [nodemon] watching path(s): *.*
Aug 22 17:34:28 ip-172-31-30-209 nodemon[1324]: [nodemon] watching extensions: js,mjs,json
Aug 22 17:34:28 ip-172-31-30-209 nodemon[1324]: [nodemon] starting `node app.js`
`

and below is status of `systemctl status socioboard-publish`

`● socioboard-publish.service - SocioBoard Publish Microservice
   Loaded: loaded (/etc/systemd/system/socioboard-publish.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2020-08-22 17:34:27 UTC; 24min ago
 Main PID: 1326 (node)
    Tasks: 11 (limit: 2348)
   CGroup: /system.slice/socioboard-publish.service
           └─1326 node /usr/bin/nodemon app.js

Aug 22 17:34:27 ip-172-31-30-209 systemd[1]: Started SocioBoard Publish Microservice.
Aug 22 17:34:28 ip-172-31-30-209 nodemon[1326]: [nodemon] 2.0.4
Aug 22 17:34:28 ip-172-31-30-209 nodemon[1326]: [nodemon] to restart at any time, enter `rs`
Aug 22 17:34:28 ip-172-31-30-209 nodemon[1326]: [nodemon] watching path(s): *.*
Aug 22 17:34:28 ip-172-31-30-209 nodemon[1326]: [nodemon] watching extensions: js,mjs,json
Aug 22 17:34:28 ip-172-31-30-209 nodemon[1326]: [nodemon] starting `node app.js`
Aug 22 17:34:36 ip-172-31-30-209 nodemon[1326]: [nodemon] clean exit - waiting for changes before restart
`

Please help me resolve the issue

**Comment by lmahendra** [comment]
figured it out..
when checked logs In user folder under socioboard-api, turned out there was an issue with mongodb password which  apparently contained "@" 
created new mongo user (with password that doesn't contain "@") and it worked!

**Comment by hcortez-bit** [comment]
hi, @lmahendra  i had the same issue, i checked my mongodb user and changed it, but its not working yet the microservices
