### ISSUE TITLE
Not able to add any social media account

### ISSUE THREAD

**Issue by lmahendra** [socioboard/Socioboard-5.0#184]
Hi,
I have configured facebook app_id & secret_key in all of the user, feeds, notification, publish folder's `config/development.json` file 

I am struggling to setup the socioboard properly. When logged in & tried to "Add Accounts" it just display a popup `OOPS Currently not able to add your account`
Logs in socioboard-web-php shows following info

`[2020-08-25 17:56:11] local.INFO: Exception :: /var/www/socioboard/socioboard-web-php/app/Modules/User/Controllers/UserController.php => 1032 => Undefined property: stdClass::$notifications  
`
Also, log file `notification/public/logs/library20200825.log` shows

`{
  ok: 0,
  errmsg: 'Skip value must be non-negative, but received: -12',
  code: 2,
  codeName: 'BadValue',
  name: 'MongoError',
  level: 'info',
  timestamp: '2020-08-25T18:08:31.777Z',
  [Symbol(mongoErrorContextSymbol)]: {}
}`

Kindly help me resolve these issues

**Comment by hcortez-bit** [comment]
Hi 
i wanted to see if you found a solution to socioboard 4 with regards to the microservices and social logins.
any help would be appreciated

**Comment by jtiebel** [comment]
have the same problem. Can anybody assist?

**Comment by liangjsbfy** [comment]
I get the same problem as you - -!

**Comment by socioboard** [comment]
Hi, Please check with Latest 5.0 releases, If you've any issues please feel free to raise issue or come in discussions,

 Thank you
