### ISSUE TITLE
http://www.socioboard.org points to nowhere and https://www.socioboard.org gives a certificate warning...

### ISSUE THREAD

**Issue by q2dg** [socioboard/Socioboard-5.0#201]
...and if I add an exception in my browser I get redirected to https://dev.empmonitor.com (!!?)

Thanks!

**Comment by sureshbabu1995** [comment]
> ...and if I add an exception in my browser I get redirected to https://dev.empmonitor.com (!!?)
> 
> Thanks!

This is Fixed, Please check the link [https://socioboard.org/](url)

**Comment by socioboard** [comment]
Hi, I hope you **look into the Latest 5.0 version**, and **we're giving weekly update** as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
