### ISSUE TITLE
Unable to create new account

### ISSUE THREAD

**Issue by dustbro** [socioboard/Socioboard-5.0#210]
Running Ubuntu 20.04 
I'm able to access the Socioboard web interface, but clicking on "create an account now" doesn't do anything. After checking the error logs in /var/www/socioboard/socioboard-web-php/storage/logs/ I'm seeing:
`[2021-02-03 07:26:22] local.INFO: Sign up Exception 201 => cURL error 3:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)
[2021-02-03 07:26:22] local.ERROR: Undefined variable: result {"exception":"[object] (ErrorException(code: 0): Undefined variable: result at /var/www/socioboard/socioboard-web-php/app/Modules/User/Controllers/UserController.php:130)`

cURL error 3 suggests my URL is not properly formatted... so which file contains this URL?

**Comment by luckisoff** [comment]
![image](https://user-images.githubusercontent.com/8510066/111662216-d7cc4780-8837-11eb-9477-99bd03d2c9ac.png)
In app/Modules/User/Controllers/UserController.php in signup method catch 
change :
`return $result to return $res`

**Comment by socioboard** [comment]
Hi, I hope you **look into the Latest 5.0 version**, and **we're giving weekly update** as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
