### ISSUE TITLE
Installation: Composer: Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by HowardCrane** [socioboard/Socioboard-5.0#216]
Hi,
I'm following instructions to install socioboard on Ubuntu 20 from [linuxbabe](https://www.linuxbabe.com/ubuntu/install-socioboard-on-ubuntu-20-04). A source of my problem _might_ be that I'm running Ubuntu 18, but I don't see why.

On **Step 10: Set Up Socioboard-web-php** I run into a problem when running `composer update` - it can't seem to find any of its requirements. See the wall of text below for my output. 
I'm a post turtle here. I don't know what composer is doing, so I need help understanding that so I can fix it.

Thank you

`Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/support v5.0.4 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.0.33 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.0.28 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.0.26 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.0.25 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.0.22 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.0.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support 5.0.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.9 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.8 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.7 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.6 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.5 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.4 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.39 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.38 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.37 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.36 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.35 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.34 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.33 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.32 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.31 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.30 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.3 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.29 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.28 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.27 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.26 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.25 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.24 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.23 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.22 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.21 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.20 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.2 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.19 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.17 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.16 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.15 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.14 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.13 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.12 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.11 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.10 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.6.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.44 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.43 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.41 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.40 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.39 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.37 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.36 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.35 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.34 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.33 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.28 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.2 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.17 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.16 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.5.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.4.9 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.4.36 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.4.27 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.4.19 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.4.17 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.4.13 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.4.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.3.4 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.3.23 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.3.16 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.3.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.7 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.6 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.45 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.43 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.37 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.32 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.31 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.28 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.27 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.26 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.25 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.24 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.21 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.19 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.2.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.8 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.6 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.41 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.31 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.30 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.28 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.25 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.22 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.20 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.2 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.16 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.13 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.1.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support 5.6.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support 5.5.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support 5.4.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support 5.3.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support 5.2.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support 5.1.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.9 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.8 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.4 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.36 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.35 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.34 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.33 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.32 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.31 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.30 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.3 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.29 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.28 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.27 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.24 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.22 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.20 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.2 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.19 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.18 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.17 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.15 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.14 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.12 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.11 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.8.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support 5.8.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.9 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.8 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.7 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.6 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.5 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.4 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.3 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.28 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.27 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.26 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.23 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.22 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.21 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.20 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.2 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.15 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.11 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.10 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support v5.7.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support 5.7.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support 5.7.19 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support 5.7.18 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - illuminate/support 5.7.17 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.9 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.8 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.7 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.6 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.5 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.4 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.3 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.29 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.28 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.27 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.26 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.25 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.24 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.23 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.22 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.21 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.20 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.2 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.19 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.18 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.17 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.16 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.15 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.14 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.13 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.12 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.11 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.10 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.1 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework v5.7.0 requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework 5.8.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework 5.7.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework 5.6.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework 5.5.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework 5.4.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework 5.3.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework 5.2.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - laravel/framework 5.1.x-dev requires ext-mbstring * -> the requested PHP extension mbstring is missing from your system.
    - ibonly/laravel-accountkit v1.2 requires illuminate/support 5.* -> satisfiable by laravel/framework[5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.x-dev, 5.8.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.12, v5.7.13, v5.7.14, v5.7.15, v5.7.16, v5.7.17, v5.7.18, v5.7.19, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.24, v5.7.25, v5.7.26, v5.7.27, v5.7.28, v5.7.29, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9], illuminate/support[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, 5.3.x-dev, 5.4.x-dev, 5.5.x-dev, 5.6.x-dev, 5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, 5.8.x-dev, v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.41, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.43, v5.2.45, v5.2.6, v5.2.7, v5.3.0, v5.3.16, v5.3.23, v5.3.4, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.36, v5.8.4, v5.8.8, v5.8.9].
    - Installation request for ibonly/laravel-accountkit ^1.2 -> satisfiable by ibonly/laravel-accountkit[v1.2].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/7.4/cli/php.ini
    - /etc/php/7.4/cli/conf.d/10-mysqlnd.ini
    - /etc/php/7.4/cli/conf.d/10-opcache.ini
    - /etc/php/7.4/cli/conf.d/10-pdo.ini
    - /etc/php/7.4/cli/conf.d/20-calendar.ini
    - /etc/php/7.4/cli/conf.d/20-ctype.ini
    - /etc/php/7.4/cli/conf.d/20-exif.ini
    - /etc/php/7.4/cli/conf.d/20-ffi.ini
    - /etc/php/7.4/cli/conf.d/20-fileinfo.ini
    - /etc/php/7.4/cli/conf.d/20-ftp.ini
    - /etc/php/7.4/cli/conf.d/20-gettext.ini
    - /etc/php/7.4/cli/conf.d/20-iconv.ini
    - /etc/php/7.4/cli/conf.d/20-json.ini
    - /etc/php/7.4/cli/conf.d/20-mysqli.ini
    - /etc/php/7.4/cli/conf.d/20-pdo_mysql.ini
    - /etc/php/7.4/cli/conf.d/20-phar.ini
    - /etc/php/7.4/cli/conf.d/20-posix.ini
    - /etc/php/7.4/cli/conf.d/20-readline.ini
    - /etc/php/7.4/cli/conf.d/20-shmop.ini
    - /etc/php/7.4/cli/conf.d/20-sockets.ini
    - /etc/php/7.4/cli/conf.d/20-sysvmsg.ini
    - /etc/php/7.4/cli/conf.d/20-sysvsem.ini
    - /etc/php/7.4/cli/conf.d/20-sysvshm.ini
    - /etc/php/7.4/cli/conf.d/20-tokenizer.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.`

**Comment by zombozo12** [comment]
Please check your `php.ini` file and find `extension=mbstring` and delete the `;` in front of the line. After that, save the file and re-run `composer update`. This should solve your problem

**Comment by socioboard** [comment]
Hi, Please check the latest requirements and installation of new code

PHP8.0^
Laravel 8.0^
Composer 2.0^

These are required and then you can install composer without any errors in latest code.
