### ISSUE TITLE
downgrade account 

### ISSUE THREAD

**Issue by pavel874** [socioboard/Socioboard-5.0#235]
when I registered for socioboard it automatically set up es the most expensive Platinum subscription. 
I came to use this as a free option. so I want to downgrade to free but when I try doing that it kicks me out with an endless loop of waiting to log back in.

how can I delete my socioboard account.  this is not what I signed up for

**Comment by sureshbabu1995** [comment]
Please check with the Current updated code. I've pushed the latest version and new updates to the bugs.
