### ISSUE TITLE
library directory is missing from the socioboard-api directory

### ISSUE THREAD

**Issue by shreyas2199** [socioboard/Socioboard-5.0#240]
library directory is missing from the socioboard-api directory. If it is renamed as Common please update in readme as well.

**Comment by sureshbabu1995** [comment]
Hi @shreyas2199 

Yes, we'll be updating the Readme files soon, and this time we'll be adding Granular documentation to make it easy for all possible ways.

**Comment by sureshbabu1995** [comment]
Hi @shreyas2199 

I think you got the latest updates.

I'm closing this ticket for now, if you've any queries feel free to open it or open a new ticket.
