### ISSUE TITLE
Recently closed issues

### ISSUE THREAD

**Issue by TechnologyClassroom** [socioboard/Socioboard-5.0#243]
I count 23 issues closed recently promoting Socioboard 5.  I am sure some issues would be resolved with a new major version.  My issue https://github.com/socioboard/Socioboard-5.0/issues/149 was not resolved.  Were these other issues also unresolved by the new version?

Will my issue be reopened or do I need to make a new duplicate issue since the issue was not resolved?

**Comment by sureshbabu1995** [comment]
Hi, @TechnologyClassroom 

Sorry for the inconvenience, it was a missed checklist category.  Now we've added the LICENSE file Please check it once.

**Comment by TechnologyClassroom** [comment]
Excellent!  Thank you!
