### ISSUE TITLE
Developer file is in docx instead of markdown

### ISSUE THREAD

**Issue by TechnologyClassroom** [socioboard/Socioboard-5.0#248]
`.docx` files are not well suited for a version control system such as a git repository. If someone have a pull request to improve the doc, they basically need to delete the file and upload a new file. The git history gets bloated very fast in this way. This is why plain text files such as markdown are commonly used for `README.md` and `INSTALL` files.

Would you like help converting the file to markdown?

**Comment by TechnologyClassroom** [comment]
Referencing https://github.com/socioboard/Socioboard-5.0/pull/147

**Comment by sureshbabu1995** [comment]
Hi, sorry for the inconvenience 

That was a simple description in that file about how it would be at the end of setup, but if you can make something similar to it in the readme file - It will help us only, 

You can share your PR; we'll be reviewing your PR and we'll merge it if everything is fine.

**Comment by TechnologyClassroom** [comment]
Beat me to it.

https://github.com/socioboard/Socioboard-5.0/blob/master/SocioBoard5.0-doc.md
