### ISSUE TITLE
pm2 start user.service.js Says [PM2][ERROR] Script not found:

### ISSUE THREAD

**Issue by dineshrggit** [socioboard/Socioboard-5.0#258]
I have followed all the steps till starting the node services.

when I try to start the node service using **pm2 start user.service.js** it gives error: **[PM2][ERROR] Script not found: /Social_board/Socioboard-5-2.0-master/socioboard-api/User/user.service.js**

This error comes for all node services Feeds, Publish, Notification, Update.

Any help will be appreciated. TIA

**Comment by sureshbabu1995** [comment]
Hi, @dineshrggit 

I've updated the config files please check it and try to run it

Yeah, there's a config object missing from user service, I'll be updating the config files very soon

or you can find that object in other services, please copy-paste it in the user config folder as well.

**Comment by sureshbabu1995** [comment]
Hi @dineshrggit 

I hope the new config is fixed your issue.

I'm closing it for now, if you've queries related to this feel free to re-open it. If you have other queries then open a new ticket.
