### ISSUE TITLE
Getting error on running user service. 

### ISSUE THREAD

**Issue by dineshrggit** [socioboard/Socioboard-5.0#259]
On running user service by npm run dev, it shows shows success in terminal 
`ip-192-168-225-153:User dinesh$ npm run dev

> suresh-babu-g@1.0.0 dev
> node ./resources/views/swagger.config.js && nodemon user.server.js

Swagger-autogen:  Success ✔ 
[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node user.server.js`
[nodemon] clean exit - waiting for changes before restart`
but getting the below error in the log file. 

error: Error: Configuration property "mailService" is not defined
at Config.get (/Users/dinesh/Sites/gp/Social_board/Socioboard-5-2.0-master/socioboard-api/Common/node_modules/config/lib/config.js:182:11)
at new userLibs (file:///Users/dinesh/Sites/gp/Social_board/Socioboard-5-2.0-master/socioboard-api/Common/Models/unAuthorized.model.js:34:59)
at file:///Users/dinesh/Sites/gp/Social_board/Socioboard-5-2.0-master/socioboard-api/User/core/unAuthorized/unAuthorized.service.js:27:26
at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
at async Loader.import (internal/modules/esm/loader.js:178:24)
at async Object.loadESM (internal/process/esm_loader.js:68:5),
level: 'error',
message: 'uncaughtException: Configuration property "mailService" is not defined\n' +
'Error: Configuration property "mailService" is not defined\n' +
' at Config.get (/Users/dinesh/Sites/gp/Social_board/Socioboard-5-2.0-master/socioboard-api/Common/node_modules/config/lib/config.js:182:11)\n' +
' at new userLibs (file:///Users/dinesh/Sites/gp/Social_board/Socioboard-5-2.0-master/socioboard-api/Common/Models/unAuthorized.model.js:34:59)\n' +
' at file:///Users/dinesh/Sites/gp/Social_board/Socioboard-5-2.0-master/socioboard-api/User/core/unAuthorized/unAuthorized.service.js:27:26\n' +
' at ModuleJob.run (internal/modules/esm/module_job.js:170:25)\n' +
' at async Loader.import (internal/modules/esm/loader.js:178:24)\n' +
' at async Object.loadESM (internal/process/esm_loader.js:68:5)',
stack: 'Error: Configuration property "mailService" is not defined\n' +
' at Config.get (/Users/dinesh/Sites/gp/Social_board/Socioboard-5-2.0-master/socioboard-api/Common/node_modules/config/lib/config.js:182:11)\n' +
' at new userLibs (file:///Users/dinesh/Sites/gp/Social_board/Socioboard-5-2.0-master/socioboard-api/Common/Models/unAuthorized.model.js:34:59)\n' +
' at file:///Users/dinesh/Sites/gp/Social_board/Socioboard-5-2.0-master/socioboard-api/User/core/unAuthorized/unAuthorized.service.js:27:26\n' +
' at ModuleJob.run (internal/modules/esm/module_job.js:170:25)\n' +
' at async Loader.import (internal/modules/esm/loader.js:178:24)\n' +
' at async Object.loadESM (internal/process/esm_loader.js:68:5)',

http://localhost:1000 is the user service url which is says could not connect to server. No errors shown in log file on hitting http://localhost:1000.

Any help will be appreciated. TIA.

**Comment by sureshbabu1995** [comment]
Hi, @dineshrggit 

Yeah, there's a config object missing from user service, I'll be updating the config files very soon

or you can find that object in other services, please copy-paste it in the user config folder as well.

**Comment by sureshbabu1995** [comment]
Hi @dineshrggit

I hope the new config is fixed your issue.

I'm closing it for now, if you've queries related to this feel free to re-open it. If you have other queries then open a new ticket.
