### ISSUE TITLE
Error: ENOENT: no such file or directory, open './resources/views/swagger-api-view.json'

### ISSUE THREAD

**Issue by FlorentPoinsaut** [socioboard/Socioboard-5.0#264]
Hello !

User, Publish, Feeds and Update services from Socioboard-5.1.0 branch don't start with this error:

```
4|update.s | Error: ENOENT: no such file or directory, open './resources/views/swagger-api-view.json'
4|update.s |     at Object.openSync (fs.js:476:3)
4|update.s |     at Object.readFileSync (fs.js:377:35)
4|update.s |     at file://~/Update/update.server.js:28:6
4|update.s |     at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
4|update.s |     at async Loader.import (internal/modules/esm/loader.js:166:24) {
4|update.s |   errno: -2,
4|update.s |   syscall: 'open',
4|update.s |   code: 'ENOENT',
4|update.s |   path: './resources/views/swagger-api-view.json'
4|update.s | }
```

One-liner workaround:
` cp Notification/resources/views/swagger-api-view.json Feeds/resources/views/  &&  cp Notification/resources/views/swagger-api-view.json User/resources/views/  &&  cp Notification/resources/views/swagger-api-view.json Publish/resources/views/  &&  cp Notification/resources/views/swagger-api-view.json Update/resources/views/ `

Regards,

**Comment by sureshbabu1995** [comment]
Hi @FlorentPoinsaut

Great To hear a fix in a bug list, Hope it will be useful for other users till we update the document.

Thank you to mention the fix.

**Comment by Jagadeesha-R** [comment]
Hi @FlorentPoinsaut,

             This swagger file generation issue, to address this please run the swagger  before staring the microservice by the following commands:
  
  1)          set node_env=development
               npm run swagger
               npm run start 

                  (or)

  2)       set node_env=development
            npm run dev

**Comment by sureshbabu1995** [comment]
Hi @FlorentPoinsaut 

I hope your issue is fixed by the latest updates.

I'm closing it for now, if you've queries related to this feel free to re-open it. If you have other queries then open a new ticket.
