### ISSUE TITLE
Error: accountSid must start with AC

### ISSUE THREAD

**Issue by FlorentPoinsaut** [socioboard/Socioboard-5.0#265]
Hello !

User service from Socioboard-5.1.0 branch doesn't start with this error:

```
0|user.ser | Error: accountSid must start with AC
0|user.ser |     at new Twilio (~/Common/node_modules/twilio/lib/rest/Twilio.js:146:11)
0|user.ser |     at new initializer (~/Common/node_modules/twilio/lib/index.js:10:10)
0|user.ser |     at new OtpVerificationLibs (file://~/Common/Models/otp-verification.model.js:12:19)
0|user.ser |     at new OtpVerificationController (file://~/User/core/otp-verification/otp-verification.service.js:15:32)
0|user.ser |     at file://~/User/core/otp-verification/otp-verification.service.js:113:16
0|user.ser |     at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
0|user.ser |     at async Loader.import (internal/modules/esm/loader.js:166:24)
```

To fix this error, you need to start the JSON node `twilio.account_sid` by `AC` in `User/config/development.json` file.

Regards,

**Comment by sureshbabu1995** [comment]
Hi @FlorentPoinsaut 

Great To hear a fix in a bug list, Hope it will be useful for other users till we update the document.

Thank you to mention the fix.

**Comment by sureshbabu1995** [comment]
Hi @FlorentPoinsaut 

 in the User config update like this, it will fix the issue

![image](https://user-images.githubusercontent.com/55544386/147207431-afc6983d-cbba-468a-99fe-f48af22061e9.png)
