### ISSUE TITLE
How to deactivate OTP verification?

### ISSUE THREAD

**Issue by mgAdler** [socioboard/Socioboard-5.0#269]
As first I don't want to use twilio (or similar). 

So I don't need OTP verifaction. How can I turn off or bypass this? 

Also there is a error in processing OTP verification (I tried to test with twilio trial subscription):

Chrome devtools:
Uncaught TypeError: phoneno.focus is not a function
    sendOTP https://MYURL/register:476
    onclick https://MYURL/register:1
    
(/socioboard-web-php/Modules/User/Resources/views/sign_up.blade.php)

**Comment by sureshbabu1995** [comment]
Hi,

We'll update the code for bypassing the OTP by using config check.

For now if you want then you need to change in FE and BE as well.


On 9/29/2021 8:09 AM, mgAdler wrote:
>
> As first I don't want to use twilio (or similar).
>
> So I don't need OTP verifaction. How can I turn off or bypass this?
>
> Also there is a error in processing OTP verification (I tried to test 
> with twilio trial subscription):
>
> Chrome devtools:
> Uncaught TypeError: phoneno.focus is not a function
> sendOTP http://url1318.globussoft.in/ls/click?upn=wVOYq0Yhcm6rutzZVQWOeMSaSyNTBpKq-2FRgu2VZTume4MzWdNFUvZK79lJ09IoH6w_OF_U31jt5HgHBh7k3Grc5s4l0BSafJ3-2Bg7Z-2FEo6yWuB-2Ffrz8MSBfWVjTBAMtAmWeEso-2FsqzwHD47mY8fimDg2Q44NX7R4t67Z0GtrEpresfDbvQ-2BNwY5fhArmDr0pBOtt6xNcOuPbWxrjXsoMtfjGZbc98kZqfCy8zy-2FSAsXacYA3aQaQDgvxhSpWNWI11WljA9ZvM9tTRq0BeIxpbg9TH8xCww-2Fu3gRVA-2FSq5w44GIwtfA7NxFDKpmTNz-2BBR-2BSbU6pqHHPEj-2BM2LcFnCuhsEtNlQ-3D-3D
> onclick http://url1318.globussoft.in/ls/click?upn=wVOYq0Yhcm6rutzZVQWOeMSaSyNTBpKq-2FRgu2VZTumeQSRX93fGwOtDs0LEQM2xvLxJx_U31jt5HgHBh7k3Grc5s4l0BSafJ3-2Bg7Z-2FEo6yWuB-2Ffrz8MSBfWVjTBAMtAmWeEso-2FsqzwHD47mY8fimDg2Q44NX7R4t67Z0GtrEpresfDbvQ-2BNwY5fhArmDr0pBOtt6x2mq5K-2BF8qRI7GqAbssZeAOi5zs2XQ6ctAwUKC-2BEbcMPJyCEPSeSXtwt99yaXUOAPXCB6EXl5HaoozoFanWOAIsH7tn7hUoqeE8-2FGBRSVZNNYoapVZMAEbJ2uce5H-2FdilvqtrXo6bji5YYGDzI6uzmA-3D-3D
>
> (/socioboard-web-php/Modules/User/Resources/views/sign_up.blade.php)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub 
> <http://url1318.globussoft.in/ls/click?upn=wVOYq0Yhcm6rutzZVQWOeAyTR0OGTuOgP7Fm7H6pahhay48TmT0HRmOtYb3kDJlOi9z0jCVe1KNzoiOlNuIWkxcleBj51uE9RiCfxd08dFM-3DwkiN_U31jt5HgHBh7k3Grc5s4l0BSafJ3-2Bg7Z-2FEo6yWuB-2Ffrz8MSBfWVjTBAMtAmWeEso-2FsqzwHD47mY8fimDg2Q44NX7R4t67Z0GtrEpresfDbvQ-2BNwY5fhArmDr0pBOtt6x8sK1xkJvaT-2B3NgHhz6Arj0nK-2FhUpfjZfSTWlVR4X9Qsjg6jLlwUSFmDuOVlL3C5bZU0id1-2F3hqY1IiiBC0fTJU3nIRFGqYH0mZUb9XWNc8jzx6pUbzB3-2Foj1KLj1o-2BsBt8itAxQqVPg-2BvqId7XgGKg-3D-3D>, or 
> unsubscribe 
> <http://url1318.globussoft.in/ls/click?upn=wVOYq0Yhcm6rutzZVQWOeJdJAXOe3xeRHvz9i2Gt-2FidGQ8Csp5o5DNksqKyd-2F4nvXg-2FE5h3-2FiE-2F7cNP3KJW9SRiSDtddXGM-2FSWqkEts7WMnkZbNnsmeIaSqvv-2BgzMTjp0Mjf-2B0Q96HRxhI6U4HYe2w-3D-3DKNT3_U31jt5HgHBh7k3Grc5s4l0BSafJ3-2Bg7Z-2FEo6yWuB-2Ffrz8MSBfWVjTBAMtAmWeEso-2FsqzwHD47mY8fimDg2Q44NX7R4t67Z0GtrEpresfDbvQ-2BNwY5fhArmDr0pBOtt6x-2B-2FHAk9drIndQwf-2Bhz8-2B3WSEGyiG1-2FmWNYi4wR9Oh2p5mSJXD7nyT4nKUeOkg4NH9FIB5dlz3VOxr8PB75u4X4ylgR25dIXE8bs5qbRDtmKvzIq18j61Pgt8wSOWT62T6w1u1rK5-2Bngb5DsBgMpPb6g-3D-3D>.
> Triage notifications on the go with GitHub Mobile for iOS 
> <http://url1318.globussoft.in/ls/click?upn=wVOYq0Yhcm6rutzZVQWOeI5Vzo2ZMDwgtDWvJG4BchYseJsDN-2FmdDdWnThNiPV4QXl7GUZKQk02bvtycOLyv6VsSSvdfMf6nKis3gdYcQphVBUwfNeHKTdbTV9cWSzo7Wg8Z-2BGZ5kg-2FCaDwecdy5eg-3D-3DbB7R_U31jt5HgHBh7k3Grc5s4l0BSafJ3-2Bg7Z-2FEo6yWuB-2Ffrz8MSBfWVjTBAMtAmWeEso-2FsqzwHD47mY8fimDg2Q44NX7R4t67Z0GtrEpresfDbvQ-2BNwY5fhArmDr0pBOtt6xbOlCdWvuJNyeCVFpKxv3-2FPJaeZ22rfeAws1gaWUC38AiZCIW2aKHKgKiTpC1u8drttjnwmN2PSnw-2F3triZa7VfAFR-2FopoOSnj5NjfkqVoV44oQ7z6GYh-2FmEExeoLoeM5q0iQhUfJPppbFOlAIsySrw-3D-3D> 
> or Android 
> <http://url1318.globussoft.in/ls/click?upn=wVOYq0Yhcm6rutzZVQWOeKC2wpnYeCr7eVQkxUteMD-2FYiSk4I8I4rzPZ0fbU9kcx4l4dKceHs3Y1loeIYJXiIDk3QEQBcNGTMhTvCUJHmIfI4FHtMhrvr-2FOvpFLGHsCPJcFExUdttouDuu6QajnFU3iyLCTLyw3tUJiMJeNAtX6QW6-2BhyZXrjeCCtNEIK-2BvUlRbvHq8AvPmX1XVJQSnEVA-3D-3DMYta_U31jt5HgHBh7k3Grc5s4l0BSafJ3-2Bg7Z-2FEo6yWuB-2Ffrz8MSBfWVjTBAMtAmWeEso-2FsqzwHD47mY8fimDg2Q44NX7R4t67Z0GtrEpresfDbvQ-2BNwY5fhArmDr0pBOtt6x15nejEeCQBa6ujp5cpebJAuI0WAmO18I3If-2BRSMSYa1ZZIZarin2-2Fdzvrfddrs2Odoq16hsuKYyB0E0-2BxZOTQSMsiE791kL8s2wQUpNzxbg2BUcQYfF4FwcWSo6aW5IWLXWWghRR-2BAkeMrdiBf11eA-3D-3D>. 
>
>

-- 
Thanking You

Best Regards,
Gogula Suresh Babu
Senior Software Engineer(TL)
*
*Bhilai Office:*          First Floor, CHPL Dream Home Apartment,
                               Near Dena Bank, Apollo Hospital Road, 
Junwani,
                               Bhilai, Dist. - Durg, Chhattisgarh, Pin - 
490020

*Bangalore Office :*2nd Floor, Lakshya Towers, KHB Colony, 5th Block
                              Koramangala, Bangalore, Karnataka, Pin - 
560095

Globussoft Global Helpline : 0788-4083007, 0788-4083008
Globussoft Bangalore Helpline : 080-41660003, +91-8550020304
*

**Comment by mgAdler** [comment]
@sureshbabu1995 are you still there?

**Comment by mgAdler** [comment]
Any updates on this @sureshbabu1995?

**Comment by sureshbabu1995** [comment]
Hi @mgAdler 

OTP is disabled, but the Twilio config has to fill up with dummy details

Hope this will fix your requirement, And I'm closing it, for now, if you've queries related to this feel free to re-open it. If you have other queries then open a new ticket.
