### ISSUE TITLE
Erro starting service

### ISSUE THREAD

**Issue by abachtold** [socioboard/Socioboard-5.0#272]
When I'm trying to star the service Im geting errors.
Using  nodemon user.server.js
[nodemon] 2.0.13
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node user.server.js`
[nodemon] clean exit - waiting for changes before restart

It stops here.

I tried the method on https://www.linuxbabe.com/ubuntu/install-socioboard-on-ubuntu-20-04
of creating the .service and starting via systemctl but i get 

● socioboard-user.service - SocioBoard User Microservice
   Loaded: loaded (/etc/systemd/system/socioboard-user.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Fri 2021-10-01 11:33:04 -03; 3s ago
  Process: 19505 ExecStart=/usr/bin/nodemon app.js (code=exited, status=203/EXEC)
 Main PID: 19505 (code=exited, status=203/EXEC)

So I can't start the services.

Before when i tried to start the service I got the 
 code: 'ERR_MODULE_NOT_FOUND'
For the change on unAuthorized.

So I used the command on:
https://github.com/socioboard/Socioboard-5.0/issues/262

What can I do to start de service?

**Comment by sureshbabu1995** [comment]
Hi @abachtold 

That's disappointing news, I've updated the installation file, can you please check it, If not sure 

My Mail ID: sureshbabu@globussoft.in

Mail me we can schedule a call to fix all your issues and I help further.

**Comment by abachtold** [comment]
I'm using the installation file. 
Somethings arent right in there still. Like the files for the nodemon is note "user.service.js" anymore, is "user.server.js" this "service" to "server" goes for the other folders too, but that is an easy change to see. 
I'll send you an e-mail.

**Comment by TechnologyClassroom** [comment]
@abachtold If you found typos in the installation file, I would suggest making a PR to fix it.

**Comment by socioboard** [comment]
Hi @abachtold 

I've updated the installation file. Check it once.

**Comment by sureshbabu1995** [comment]
Hi @abachtold

I've updated the installation file. Check it once.

**Comment by sureshbabu1995** [comment]
Hi @abachtold 

I hope the new update fixed your issue.

I'm closing it for now, if you've queries related to this feel free to re-open it. If you have other queries then open a new ticket.
