### ISSUE TITLE
Lots of Issues when try to run nodemon "microservices"

### ISSUE THREAD

**Issue by hamza4522** [socioboard/Socioboard-5.0#290]
Please update your rep completely. I am facing lots of file missing errors. The web app runs fine but is unable to run any microservice especially user.js. it gives lots of file missing error, config.shared.js file is missing, Dailymotion files are missing

**Comment by socioboard** [comment]
Hi @hamza4522 

Sorry for the inconvenience Let me update the files..

**Comment by hamza4522** [comment]
Thankx for updating the files

**Comment by sureshbabu1995** [comment]
Hi @hamza4522 ,

 I've updated the files Please pull the latest code and try to run it.

If you still have a problem feel free to re-open or send a mail to `sureshbabu@socioboard.com`
