### ISSUE TITLE
Publish microservice error (on schedule function)

### ISSUE THREAD

**Issue by arrianda** [socioboard/Socioboard-5.0#300]
Publish microservice always error everyday when schedule crons running due to code at socioboard-api/Publish/core/schedule/schedule-base.js on line 43, where there it call a function "remove3DaysBeforeScheduleInfo", but this function is not declared (on console I got this.remove3DaysBeforeScheduleInfo is not a function).

How do I fix it?
Screenshot below

Thanks

![image](https://user-images.githubusercontent.com/17354390/144577402-25ea1d6f-36ac-46e2-8be4-200610e31534.png)

**Comment by sureshbabu1995** [comment]
Hi @arrianda

**Comment by arrianda** [comment]
Hello @sureshbabu1995 , and thanks for the reply. I already done that tutorial and able to run at least user and publish safely. The problem is like I said before, the publish microservice terminated each day because of cron task. Is there any spesific that must I do or I check to fix it?

**Comment by sureshbabu1995** [comment]
Hi, @arrianda 

Please check the new code, we've updated the crons and the functionality.

If you still have a problem, please re-open it, we can have a call and fix it directly at your server.

**Comment by arrianda** [comment]
Hello, thanks for the news. Somehow it didn't fix.
May I know where function "remove3DaysBeforeScheduleInfo" comes from? Is it from library or socioboard api? Because I can't found any reference to that function.
