### ISSUE TITLE
Some task take very long time to finish

### ISSUE THREAD

**Issue by arrianda** [socioboard/Socioboard-5.0#303]
I have problem where some task take really long time to finish, which is
1. Unbind social url /v1/socialaccount/delete-social-profile
2. Bind twitter using url /v1/socialaccount/add-social-profile

Some of log that I got
DELETE /v1/socialaccount/delete-social-profile?teamId=2&AccId=40 200 75 300842.371 ms
DELETE /v1/socialaccount/delete-social-profile?teamId=1&AccId=2 200 75 301694.563 ms

**Comment by sureshbabu1995** [comment]
Hi @arrianda 

Let me check with it, we'll use event emitters if it's really taking time.

**Comment by arrianda** [comment]
hello, any update?

**Comment by arrianda** [comment]
Hello, I found the cause. Because my setting for notification (especially notification url config on user microservice is wrong). After fix it, it work fast
