### ISSUE TITLE
Error upload video on Publish microservice 

### ISSUE THREAD

**Issue by arrianda** [socioboard/Socioboard-5.0#304]
I tried to upload a video using Publish microservice /v1/upload/media and won't get uploaded (I still able to upload image there). My video only 2 secs and it a valid video (.mp4)
I check some log and got this:

`{
  killed: false,
  code: 127,
  signal: null,
  cmd: 'ffmpeg -i ../../media/videos/1639040383.mp4 -r 3 -s 0x0 -aspect NaN:NaN -vframes 1 -filter_complex "scale=iw*sar:ih, pad=max(iw\\,ih*(NaN/NaN)):ow/(NaN/NaN):(ow-iw)/2:(oh-ih)/2:black" ../../media/thumbnails/thumb_1639040384_%d.jpg',
  level: 'info',
  message: 'error  Command failed: ffmpeg -i ../../media/videos/1639040383.mp4 -r 3 -s 0x0 -aspect NaN:NaN -vframes 1 -filter_complex "scale=iw*sar:ih, pad=max(iw\\,ih*(NaN/NaN)):ow/(NaN/NaN):(ow-iw)/2:(oh-ih)/2:black" ../../media/thumbnails/thumb_1639040384_%d.jpg\n' +
    '/bin/sh: 1: ffmpeg: not found\n',
  stack: 'Error: Command failed: ffmpeg -i ../../media/videos/1639040383.mp4 -r 3 -s 0x0 -aspect NaN:NaN -vframes 1 -filter_complex "scale=iw*sar:ih, pad=max(iw\\,ih*(NaN/NaN)):ow/(NaN/NaN):(ow-iw)/2:(oh-ih)/2:black" ../../media/thumbnails/thumb_1639040384_%d.jpg\n' +
    '/bin/sh: 1: ffmpeg: not found\n' +
    '\n' +
    '    at ChildProcess.exithandler (child_process.js:383:12)\n' +
    '    at ChildProcess.emit (events.js:400:28)\n' +
    '    at maybeClose (internal/child_process.js:1058:16)\n' +
    '    at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)',
  timestamp: '2021-12-09T08:59:44.173Z'
}
{
  message: ': ---- : unhandledRejection : ---- : Error: Command failed: ffmpeg -i ../../media/videos/1639040383.mp4 -r 3 -s 0x0 -aspect NaN:NaN -vframes 1 -filter_complex "scale=iw*sar:ih, pad=max(iw\\,ih*(NaN/NaN)):ow/(NaN/NaN):(ow-iw)/2:(oh-ih)/2:black" ../../media/thumbnails/thumb_1639040384_%d.jpg\n' +
    '/bin/sh: 1: ffmpeg: not found\n' +
    ' : ---- : Unhandled Rejection at Promise : ---- : [object Object] : ---- :',
  level: 'error',
  timestamp: '2021-12-09T08:59:44.181Z'
}`

Is there any way to fix it?

**Comment by sureshbabu1995** [comment]
Hi @arrianda 

It requires FFMPEG for video uploads and thumbnail creation.

**Comment by sureshbabu1995** [comment]
Hi @arrianda 

I hope your issue got fixed, if not feel free to re-open this.

Have a good time with SocioBoard.
