### ISSUE TITLE
wrong imports throwing error

### ISSUE THREAD

**Issue by kundan1301** [socioboard/Socioboard-5.0#310]
https://github.com/socioboard/Socioboard-5.0/blob/d357f8acb76578ac95c91cb6c6fd4cea95ecfa55/socioboard-api/User/resources/routes/public.routes.js#L6

`import unauthorized from '../../core/unauthorized/unauthorized.routes.js';`
should be
`import unauthorized from '../../core/unAuthorized/unAuthorized.routes.js';`

**Comment by sureshbabu1995** [comment]
Hi @kundan1301 

Thanks for the update, please check now we've updated the code. & if you still think it's having the same error, then please raise the ticket.
