### ISSUE TITLE
Tasks take very long time to finish

### ISSUE THREAD

**Issue by hamza4522** [socioboard/Socioboard-5.0#311]
Tasks take a very long time to finish and microservices e.g publish, users stop automatically after sometimes.. kindly fix it

**Comment by sureshbabu1995** [comment]
Hi, please share the config of the server and if you can share the time taken, I'll update ASAP.

I'll update user microservice ,

**Comment by sureshbabu1995** [comment]
Hi @hamza4522 

I hope this is not an issue now, after making too many deployments (Updates) to code.

If you still think it is, then feel free to re-open it.
