### ISSUE TITLE
Linux case on unAuthorized folders 

### ISSUE THREAD

**Issue by dustbro** [socioboard/Socioboard-5.0#315]
Looks like there's still a few instances of camel case errors on the folder unAuthorized.

**Comment by socioboard** [comment]
HI @dustbro 

Let me check with it, But most of the cases it got updated with latest code, if you've any logs it would be better or else I'll check with Linux server and update it ASAP.

**Comment by justinshaw** [comment]
Looks like it's in `/opt/socioboard-api/User/core/unauthorized/unauthorized.routes.js`

```
api_1    | /root/.pm2/logs/user.server-out.log last 15 lines:
api_1    | /root/.pm2/logs/user.server-error.log last 15 lines:
api_1    | 0|user.ser | Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/opt/socioboard-api/User/core/unauthorized/unauthorized.routes.js' imported from /opt/socioboard-api/User/resources/routes/public.routes.js
api_1    | 0|user.ser |     at new NodeError (node:internal/errors:371:5)
api_1    | 0|user.ser |     at finalizeResolution (node:internal/modules/esm/resolve:416:11)
api_1    | 0|user.ser |     at moduleResolve (node:internal/modules/esm/resolve:932:10)
api_1    | 0|user.ser |     at defaultResolve (node:internal/modules/esm/resolve:1044:11) 
api_1    | 0|user.ser |     at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
api_1    | 0|user.ser |     at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
api_1    | 0|user.ser |     at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
api_1    | 0|user.ser |     at link (node:internal/modules/esm/module_job:75:36) {
api_1    | 0|user.ser |   code: 'ERR_MODULE_NOT_FOUND'
api_1    | 0|user.ser | }
```

**Comment by dustbro** [comment]
I wish I took note. It was in 5 or 6 different files.

**Comment by sureshbabu1995** [comment]
Hi @dustbro 

Yes, it was in multiple files before, as I was doing with windows env. 

But I replaced this code with our server code which is ubuntu, it should have been fixed in all files by now.

If not please feel free to re-open it, I'll recheck it once more time with a different OS.

**Comment by sureshbabu1995** [comment]
Hi @dustbro 

Yes, it was in multiple files before, as I was doing with windows env. 

But I replaced this code with our server code which is ubuntu, it should have been fixed in all files by now.

If not please feel free to re-open it, I'll recheck it once more time with a different OS.
