### ISSUE TITLE
Unable to create new users and sign up with other methods giving " Sorry some Error occurred , Please reload the page "

### ISSUE THREAD

**Issue by sifat18** [socioboard/Socioboard-5.0#327]
While trying to log with google sign up, It displays "Sorry some Error occurred , Please reload the page " this error. In the console it is displaying this.
`Uncaught ReferenceError: SBAppSettings is not defined
    <anonymous> http://smm.grit0.com/js/main.js:328
    mightThrow http://smm.grit0.com/plugins/global/plugins.bundle.js:3557
    process http://smm.grit0.com/plugins/global/plugins.bundle.js:3625
Uncaught ReferenceError: reset is not defined
    <anonymous> http://smm.grit0.com/login:611
`

when I try to register a new user it keeps showing me this error

`sign_up.js:209 Uncaught ReferenceError: apiUrl is not defined
    at HTMLInputElement.<anonymous> (sign_up.js:209:22)
    at HTMLDocument.dispatch (plugins.bundle.js:5237:27)
    at HTMLDocument.elemData.handle (plugins.bundle.js:5044:28)
(anonymous) @ sign_up.js:209
dispatch @ plugins.bundle.js:5237
elemData.handle @ plugins.bundle.js:5044`

**Comment by adambicknell** [comment]
What is your OS?

I had this same error, but mine was for different reasons.

Are you setting the Node Env when starting the servers?


`For windows environment`
```code
    set NODE_ENV=development
```

`For linux || mac environment`
```code
    export NODE_ENV=development
```

**Comment by sifat18** [comment]
@adambicknell  Thanks for the response.  I migrated to version 5 and now the 2nd error is gone. But still getting the first error. Did you get any error for google sign up? also I am still unable to register a new user. When I try to register after filling up it is giving me a undefined notification and getting this error 
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/v1/check-username-availability?username=iojfoiajf. (Reason: CORS request did not succeed). Status code: (null).
3
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:3000/v1/check-email-availability?email=ibnsifat@gmail.com. (Reason: CORS request did not succeed). Status code: (null).`

Were you able to register ?

**Comment by adambicknell** [comment]
I got that error when I was accessing the site from 127.0.0.1:8000 and trying to access localhost:3000. 

If you're doing something similar, You just need to use localhost:8000 in your browser so you don't get the CORS error.

However, I'm getting an issue with authorisation. It is creating the users, but still failing on the front end!

**Comment by adambicknell** [comment]
Also, I didn't try the Google login. Did you get any further with it?

I think the issue I'm having atm is to do with Mail setup... it fails just before

`const mailDetails = await unauthorizedLibs.sendMail(
          responseData,
          planDetails.plan_name
        );` on line 141 of `socioboard-api/User/core/unAuthorized/unauthorized.service.js`
        
Will update you if I get it working and let me know if you're stuck and I'll try and get you up to the same point I'm at!

**Comment by sureshbabu1995** [comment]
HI @sifat18 I think you got the answer, if not please check with the latest Updated code.

I even updated g-mail config in recent, Please check it again.

If you still have a problem, feel free to re-open it.

**Comment by sersart** [comment]
> http://localhost:3000/

Hi,
I got that error too. How to fix it? 
Do i have to use a public domain in .env file for  API_URL= http://localhost:3000/ and redirect it to http://localhost:3000/  apache config?
Thanks
