### ISSUE TITLE
Typo in filename

### ISSUE THREAD

**Issue by TechnologyClassroom** [socioboard/Socioboard-5.0#337]
In the `Installatin.sh`filename `Installation` is misspelled, but typically you would abbreviate the name as `install.sh` instead.

**Comment by sureshbabu1995** [comment]
Hi @TechnologyClassroom 

Thanks for the update, Let me update and push it.

**Comment by sureshbabu1995** [comment]
Hi @TechnologyClassroom 

I've Updated the installation shell file and fixed the spelling mistake of the File name
