### ISSUE TITLE
Twitter Video Chunk Upload

### ISSUE THREAD

**Issue by arrianda** [socioboard/Socioboard-5.0#355]
Hello, can you help me or update socioboard to upload video post using chunked upload? Socioboard's current function don't use chunk and no "media_category" parameter set when intialize video upload, which make uploadable video size limit only 30sec, when if using "media_category" parameter and chunked upload, we can extend it to 2 minutes.

I can't do it myself since I'm not proficient in node.js

**Comment by sersart** [comment]
Hi [arrianda](https://github.com/arrianda)

I am trying to install a socioboard on my local mac for development.
Do you working with app in local computer? I have a problem with php. I can not start web-php
Can you help me?
Thanks

**Comment by arrianda** [comment]
> Hi [arrianda](https://github.com/arrianda)
> 
> I am trying to install a socioboard on my local mac for development. Do you working with app in local computer? I have a problem with php. I can not start web-php Can you help me? Thanks

I never try on mac though. Only at local Windows and server Linux. Try to follow installation guide. Then you can post your problem and I will try to help of I can

**Comment by sersart** [comment]
I already fixed and it fine now.
Thank you

**Comment by sureshbabu1995** [comment]
Hi @sersart 

I think you got it. Now I'm closing this ticket.

If you've any queries regarding this feel free to re-open it, if you have any other queries feel free to open a new ticket.
