### ISSUE TITLE
Can't seem to create account because of OTP issue - Phone Number Invalid or too long due to regex (Belgium)

### ISSUE THREAD

**Issue by kenjibailly** [socioboard/Socioboard-5.0#359]
https://github.com/socioboard/Socioboard-5.0/blob/96f90cb521273081f4615b6ae001452fbd3208ec/socioboard-web-php/Modules/User/Resources/views/login.blade.php#L479

This regex makes it that I need to write in this format:

475 123 456 7

This is too long and so does the system say: 

![image](https://user-images.githubusercontent.com/9883910/162204705-b35b08c0-4c4d-4f6e-82ba-2e9b5363b4eb.png)

--- 

While in reality the number is without he 7 at the end and in this format:

475 123 456

Weirdly enough, the regex doesn't let me enter this number without giving me this error:

![image](https://user-images.githubusercontent.com/9883910/162204875-06ddef53-6c33-4fed-be3c-aa1118f37b6a.png)

--- 

Neither is it possible to enter the full "normal" number since the regex doesn't allow a 0 as the first number being:

0475 123 456

But I'm guessing that is because the system puts +32 in front?

The full international phone number would be 

+32 475 123 456

---

I'm wondering how I can make my account / how to bypass this?

P.S. I'm selfhosting

EDIT: I tried to change the regex in that file, but I get "Some error occured, Can not send the OTP"

**Comment by arrianda** [comment]
- I think you can remove entirely OTP function and change the register to bypass it (directly call register API). 
- Use swagger function of User microservice to directly register a member

**Comment by kenjibailly** [comment]
Got it fixed now using the new Docker Setup.
