### ISSUE TITLE
Gettin this error when running "     composer install & php artisan key:generate " command in `socioboard-web-php`

### ISSUE THREAD

**Issue by hamza4522** [socioboard/Socioboard-5.0#382]
79 package suggestions were added by new dependencies, use `composer suggest` to see details.
Package swiftmailer/swiftmailer is abandoned, you should avoid using it. Use symfony/mailer instead.
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Illuminate\Contracts\Container\BindingResolutionException

  Target class [CommandMakeCommand] does not exist.

  at vendor/laravel/framework/src/Illuminate/Container/Container.php:879
    875▕
    876▕         try {
    877▕             $reflector = new ReflectionClass($concrete);
    878▕         } catch (ReflectionException $e) {
  ➜ 879▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    880▕         }
    881▕
    882▕         // If the type is not instantiable, the developer is attempting to resolve
    883▕         // an abstract type such as an Interface or Abstract Class and there is

      +13 vendor frames
  14  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
ubuntu@ip-172-31-34-153:~/Socioboard-5.0/socioboard-web-php$ use Nwidart\Modules\Commands;

**Comment by vaughngx4** [comment]
Hi, are you using composer version 2 or newer?

**Comment by hamza4522** [comment]
i am using composer latest version 2.3.9

**Comment by vaughngx4** [comment]
> its working with php 7.4 ... its giving this issue with php8.0&8.1
> 

Strange, seems there was a related issue with the module though. https://github.com/nWidart/laravel-modules/issues/1355

**Comment by vaughngx4** [comment]
Although I am using php8 in the Docker container.
