### ISSUE TITLE
Unable to login when configured with Apache2 HTTP Server

### ISSUE THREAD

**Issue by NareshRdyC** [socioboard/Socioboard-5.0#390]
When I run web PHP application using Apache2 HTTP server then its not able to communicate to login service. But same thing is working when I use php artisan serve. Is there any specific configuration I need to do and any extension libs I need to add to work. I am using Windows Server 2019.

**Comment by vaughngx4** [comment]
@NareshRdyC I would strongly suggest sticking to php artisan serve. I have yet to dig into the frontend and we have little to no support from developers. If you're convinced you want to use apache I'd look into converting a Laravel application into a LAMP application, but this would require some development/config.

Look into using Hyper-V to spin up a linux machine and run it in there. If you're having trouble, try the automated Docker deployment using ansible on my fork.

**Comment by NareshRdyC** [comment]
@vaughngx4 : Thank you for quick reply. I have noted what you mentioned. I have read in multiple posts that Artisan server is not recommended for production/live. What server (Opensource) I need to use in production, which I can configure to access using https. Thank you.

**Comment by vaughngx4** [comment]
@NareshRdyC I see your point. Give me some time, I'll see what I can do.

**Comment by vaughngx4** [comment]
@NareshRdyC I've pushed changes to my fork. All in production env now :)

**Comment by vaughngx4** [comment]
Using nginx and php-fpm instead of apache. If all is well you can mark the issue as solved.

**Comment by NareshRdyC** [comment]
@vaughngx4 I will check it and update status here. Thank you.

**Comment by NareshRdyC** [comment]
> Using nginx and php-fpm instead of apache. If all is well you can mark the issue as solved.

When I try above getting error 404 Not Found. But other sample PHP files it was working. Is there a way to run Artisan using valid https certificates. Thank you.

**Comment by vaughngx4** [comment]
@NareshRdyC The root folder should be `socioboard-web-php/public`. The `server.php` file is only for artisan. See my fork in `docker/socioboard-web` there is a full setup with nginx as the web server.

**Comment by NareshRdyC** [comment]
@vaughngx4 Will these changes what was suggested in docker/socioboard-web works in windows server also without using docker. Thank you.

**Comment by vaughngx4** [comment]
> @vaughngx4 Will these changes what was suggested in docker/socioboard-web works in windows server also without using docker. Thank you.

Yes. If you can set up NGINX with php-fpm you can use my nginx.conf files to serve the frontend in production environment. How are you setting it up? Natively on Windows or using Hyper-V and a VM? If you're using a VM simply install a linux distro and search the internet for how to get nginx and php-fpm installed and working. You could probably use Apache but I haven't myself so I won't be able to assist with that.

**Comment by NareshRdyC** [comment]
> @vaughngx4 Will these changes what was suggested in docker/socioboard-web works in windows server also without using docker. Thank you.

This suggestion helped me to solve configuration issue. Thank you quick suggestions.
