### ISSUE TITLE
PM2 Popup non-stop

### ISSUE THREAD

**Issue by iamwinner422** [socioboard/Socioboard-5.0#403]
When starting micro-sevices with pm2 using this command 
`set NODE_ENV=development & cd ./socioboard-api/User & pm2 start user.server.js & cd ../Feeds & pm2 start feeds.server.js & cd ../Publish & pm2 start publish.server.js & cd ../Notification & pm2 start notify.server.js & cd ../Update & pm2 start update.server.js & pm2 status`,  Terminals open and close automatically non-stop.

Is it a pm2 problem?

**Comment by sureshbabu1995** [comment]
Hi @iamwinner422 

There are no such issues, it will run the process smoothly, 
but I doubt that, are you using a window or Linux-based system if windows it will work, if Linux, replace & with && 

For a simple and easy solution, you can just run this single line multiple times with till & (run every command separated by & operator).

Hope this will solve your issue.

Thank you for your interest and hope you like it.
