### ISSUE TITLE
Own SMTP service

### ISSUE THREAD

**Issue by Quiwy** [socioboard/Socioboard-5.0#415]
Hi,
We are trying to setup Socioboard 5.0 using the following documentation : https://github.com/socioboard/Socioboard-5.0/blob/master/Docker.README.md .

The service is responding well, but we can't create an account as we don't know where to setup our own smtp gateway. After searching for a while, we would like to know if it's possible to use a setup where we define smtp parameters in the .env file, or is it mandatory to use SENDGRID / GMAIL to use this project ?

Thank you in advance for your answer.
Best regards

**Comment by sureshbabu1995** [comment]
Hi @Quiwy 

As of now, we're allowing only 2 types of mail services (SendGrid & Email). We're sorry for not adding any SMTP as of now, but I guess, this would be easy to set up in the mail service file if you've any basic knowledge 

and in the future update, we'll definitely add it :)

-- For now please feel free to use the free quote of SendGrid or Email service (both are safe and secure).

**Comment by Quiwy** [comment]
Thank you for your answer.
