### ISSUE TITLE
apps domain

### ISSUE THREAD

**Issue by demetch** [socioboard/Socioboard-5.0#89]
hello ,
pleas what is the value for app Domain and ApiDomain in Appsettings.json 

my domain(hostname) is afrimonitoring.com
"AppSettings": {
    "Domain": "http://localhost:9821",
    "ApiDomain": "http://localhost:6361",

PLEASE HELP ME ASAP

Regards

**Comment by demetch** [comment]
Nobody to help me ?

**Comment by socioboard** [comment]
Sorry for the delay, 
Please replace the following the details in Appsettings.json according to your domain

{
  "ApplicationInsights": {
    "InstrumentationKey": ""
  },
  "ConnectionStrings": {
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "AppSettings": {
    "Domain": "https://www.afrimonitoring.com/",
    "ApiDomain": "<Your Api domain>",


    "FacebookAuthUrl": "",
    "FacebookClientId": "",
    "FacebookClientSecretKey": "",
    "FacebookRedirectUrl": "https://www.afrimonitoring.com/FacebookManager/Facebook",



    "GoogleConsumerKey": "",
    "GoogleConsumerSecret": "",
    "GoogleApiKey": "",
    "GoogleRedirectUri": "https://www.afrimonitoring.com/GoogleManager/Google",

    "pinterestConsumerKey": "",
    "pinterestConsumerScreatKey": "",
    "pinterestRedirectionUrl": "https://www.afrimonitoring.com/PinterestManager/Pinterest",
    "PinterestAuthUrl": "https://api.pinterest.com/oauth/?response_type=code",

    "twitterConsumerKey": "",
    "twitterConsumerScreatKey": "",
    "twitterRedirectionUrl": "https://www.afrimonitoring.com/TwitterManager/Twitter",


    "InstagramClientKey": "",
    "InstagramClientSec": "",
    "InstagramCallBackURL": "",
    "InsagramAuthUrl": "",

    "LinkedinApiKey": "",
    "LinkedinSecretKey": "",
    "LinkedinCallBackURL": "",
    "callBackUrl": "",
    "failUrl": "",
    "cancelurl": "",
    "PaypalURL": "https://www.paypal.com",
    "paypalemail": "",
    "PayUMoneyURL": "https://secure.payu.in/",
    "PayuMoneyemail": "",
    "payurl": "https://www.payumoney.com",
    "surl": "",
    "key": "",
    "salt": "",
    "moneyconvertion": "",
    "AuthorizationKey": ""

  }
}

**Comment by socioboard** [comment]
Het demetch, 
If you still same issue, please updagrade to the new version.

**Comment by socioboard** [comment]
Hi, I hope you look into the Latest 5.0 version, and we're giving weekly update as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
