### ISSUE TITLE
Run services

### ISSUE THREAD

**Issue by demetch** [socioboard/Socioboard-5.0#90]
Hello Sir @socioboard 

how to run Domain.socioboard ? Socioboard.facebook ? Socioboard.google, Socioboarddataservices and others ?

regards

**Comment by demetch** [comment]
getting this error

An unhandled exception has occurred: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Socioboard.Controllers.LinkedinManagerController.<AuthenticateLinkedin>d__3.MoveNext() in C:\Users\Administrator\Documents\Visual Studio 2015\Projects\Socioboard-Core-3.0-3.0.52\src\Socioboard\Controllers\LinkedinManagerController.cs:line 109
--- End of stack trace from previous location where exception was thrown ---

**Comment by socioboard** [comment]
HI demetch
You need to create developer apps for these social networks
and use those keys and secrets to your web app after that they work
These are the class libraries for different networks
These libraries used for social media authentication and apis for your app

Thanks

**Comment by demetch** [comment]
Hi sir, 
I've done all this, but getting redirect error with 500 error,  It's seem that socioboard did not Read those keys and secret. 
Try register tour self with Facebook or google,  and see error. Use: coralmonitoring. com

Waiting

**Comment by demetch** [comment]
Hello sir @socioboard 
i thinks that the script have many issue, .
we need to pay for installation , it's urgent. tell me your paypal .

waiting your reply

**Comment by demetch** [comment]
error, how to solved

 [Error] Connection id ""0HLGJMBNLFREF"": An unhandled exception was thrown by the application.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Socioboard.Controllers.FacebookManagerController.<AddFacebookAcc>d__6.MoveNext() in C:\Users\Administrator\Documents\Visual Studio 2015\Projects\Socioboard-Core-3.0-3.0.52\src\Socioboard\Controllers\FacebookManagerController.cs:line 234
--- End of stack trace from previous location where exception was thrown ---

**Comment by socioboard** [comment]
We have upgraded the new version to 4.0 which includes nodeja and php. Please upgrade it.

**Comment by socioboard** [comment]
Hi, I hope you look into the Latest 5.0 version, and we're giving weekly update as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
