### ISSUE TITLE
URL Redirect

### ISSUE THREAD

**Issue by demetch** [socioboard/Socioboard-5.0#91]
Dear sir,
i've set social keys and secret, but when trying to add a profile i get blank redirect URL: 

https://coralmonitoring.com/Index/&client_id=&redirect_uri=&response_type=code

please help

**Comment by demetch** [comment]
i think that, the values of appsettings.json are not available in others files where variables are call ,
that is while i'm getting blank redirection ?
1. please how to solved this
2. what is the stable version of SOCIOBOARD ?

**Comment by demetch** [comment]
@socioboard  need your reply please !!!

**Comment by demetch** [comment]
@socioboard  @RajGlobussoft @swetasb 
please getting this error 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Socioboard.Controllers.FacebookManagerController.<AddFacebookAcc>d__6.MoveNext() in C:\Users\Administrator\Documents\Visual Studio 2015\Projects\Socioboard-Core-3.0-3.0.52\src\Socioboard\Controllers\FacebookManagerController.cs:line 234

help me

**Comment by socioboard** [comment]
HI demetch
Your issue is regarding facebook app credentials
Please create an app in facebook developers by your domain reference, and then add that app credentials to your project
This issue will be solved.

Thanks

**Comment by demetch** [comment]
@socioboard 
Hello sir, now getting this error:

Invalid Scopes: user_events, user_friends, user_likes, user_managed_groups, user_photos, user_posts, user_tagged_places, user_videos. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: 

how to solved this ? please witch scope to use ?

**Comment by demetch** [comment]
@socioboard  geting google acess token not found error ...
how to solved this also 

regards

**Comment by demetch** [comment]
[Information] Error reading JObject from JsonReader. Path '', line 0, position 0.
2018-09-13 01:42:27.653 -07:00 [Error]    at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Api.Socioboard.Controllers.GoogleController.GoogleLogin(String code

**Comment by arvs47** [comment]
remove this user_managed_groups and try to refer facebook documentations for scopes

**Comment by socioboard** [comment]
Hi, I hope you look into the Latest 5.0 version, and we're giving weekly update as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
