### ISSUE TITLE
Database SQL error [ 1067 - Invalid default value for 'forgotPasswordExpireDate' ]

### ISSUE THREAD

**Issue by frey1esm** [socioboard/Socioboard-5.0#92]
I got this error when executing the SQL file.

`1067 - Invalid default value for 'forgotPasswordExpireDate', Time: 0.179000s`

from this field definition:

`forgotPasswordExpireDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,`

and thus the 'user' table did not get created.

**Comment by socioboard** [comment]
Hi, I hope you **look into the Latest 5.0 version**, and **we're giving weekly update** as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
