### ISSUE TITLE
Install on localhost using phpmyadmin

### ISSUE THREAD

**Issue by wmike1503** [socioboard/Socioboard-5.0#93]
Hi all,

I'm trying to take a look at Socioboard.   I use phpmyadmin.  I can't seem to work out how to setup the database - the instructions for heidisql don't seem to work.

Any suggestions anyne, please.

Cheers,

Mike

**Comment by wmike1503** [comment]
Tried loading the files into Visual Studio 2015 Community edition - just results in errors - nothing gets loaded.

**Comment by Quin452** [comment]
In phpMyAdmin you need to manually create the database that you want to use, and make sure it matches up with db_name in the config/connection files.

You can run the migrate to create the tables.

**Comment by socioboard** [comment]
Hi, I hope you **look into the Latest 5.0 version**, and **we're giving weekly update** as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
