### ISSUE TITLE
missing values

### ISSUE THREAD

**Issue by demetch** [socioboard/Socioboard-5.0#94]
Hello sir,
the appsettings values is not loading in all over the project ...please how to solved this ?
_appSettings.ApiDomain

"AppSettings": {
    "Domain": "https://coralmonitoring.com",
    "ApiDomain": "https://api.coralmonitoring.com",

**Comment by socioboard** [comment]
Hi, I hope you **look into the Latest 5.0 version**, and **we're giving weekly update** as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
