### ISSUE TITLE
Account verification email not working

### ISSUE THREAD

**Issue by candresct** [socioboard/Socioboard-5.0#95]
Hi

I installed socioboard in my local computer, when I create a new user, my database is loaded with the new user, but, I do not ever receive in the  email account the message for confirmation, therefore I can not verify  the user.

I appreciate the help.

**Comment by andresct46** [comment]
Hi team socioboard

Some help to this ?

**Comment by AishwaryaMurali** [comment]
Hello,
This issue is solved in Socioboard 4.0 version.
Please pull the latest code from Socioboard 4.0, node.js and php version.

**Comment by socioboard** [comment]
Hi, I hope you **look into the Latest 5.0 version**, and **we're giving weekly update** as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
