### ISSUE TITLE
Error adding to Groups table

### ISSUE THREAD

**Issue by ozgecolak** [socioboard/Socioboard-5.0#98]
In Register function in UserController, user record is added to user table successfully but after that when adding record to groups table i get this error on 2282nd line  - dbRepository.Add(group) - in UserController.cs:

{"could not insert: [Domain.Socioboard.Models.Groups#0][SQL: INSERT INTO Groups (groupName, createdDate, adminId, id) VALUES (?, ?, ?, ?)]"}

"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Groups (groupName, createdDate, adminId, id) VALUES ('Socioboard', '2019-01-30 1' at line 1"
"   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()\r\n   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)\r\n   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)\r\n   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()\r\n   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)\r\n   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()\r\n   at NHibernate.AdoNet.AbstractBatcher.ExecuteNonQuery(IDbCommand cmd)\r\n   at NHibernate.AdoNet.NonBatchingBatcher.AddToBatch(IExpectation expectation)\r\n   at NHibernate.Persister.Entity.AbstractEntityPersister.Insert(Object id, Object[] fields, Boolean[] notNull, Int32 j, SqlCommandInfo sql, Object obj, ISessionImplementor session)"

I checked the db and i saw the user record is created in user table but no record is created in groups table.

**Comment by ozgecolak** [comment]
Which mysql version are you using? I googled it and it may be about the version.

**Comment by socioboard** [comment]
Hi we made **a Major Update**, I hope you **look into the Latest 5.0 version**, and **we're giving weekly update** as well and this won't be considerable issue in that latest code, If you've any issue, feel free to open a bug and we'll be helping you..
